/*******************************************************
This program was created by the CodeWizardAVR V4.02 
Automatic Program Generator
© Copyright 1998-2024 Pavel Haiduc, HP InfoTech S.R.L.
http://www.hpinfotech.ro

Project : 
Version : 
Date    :  8/14/2024
Author  : 
Company : 
Comments: 


Chip type               : ATmega16
Program type            : Application
AVR Core Clock frequency: 16.000000 MHz
Memory model            : Small
External RAM size       : 0
Data Stack size         : 256
*******************************************************/

// I/O Registers definitions
#include <mega16.h>

// 1 Wire Bus interface functions
#include <1wire.h>

// DS1820 Temperature Sensor functions
#include <ds1820.h>

// Bit-Banged I2C Bus functions
#include <i2c.h>

// Alphanumeric LCD functions
#include <alcd.h>
// Delay functions
#include <delay.h>

// Declare your global variables here
#define DQ_0    PORTC.7=0
#define DQ_1    PORTC.7=1
#define DQ_OUT  DDRC.7=1
#define DQ_IN   DDRC.7=0
#define DQ      PINC.7

// We know from the slides that the AT24C02 EEPROM has the device address of 0xA0.
#define EEPROM_BUS_ADDRESS 0xA0


// my own eeprom_read
/* read a byte from the EEPROM */
// start with a start signal generated by the i2c_start() function. 
// write the slave device address to the I2C bus. it's a 7-bit address, with the MSB represents
//      MSB = 0: master write data to slave
//      MSB = 1: master read data from slave
// it seems that if we would like to read the data from the slave's arbitrary address, we need to write
// the address to the slave first before we read it from the bus.
// why we don't need to stop before another start?
unsigned char eeprom_read(unsigned char address) 
{
unsigned char data;
// Start signal 
i2c_start();
// directly use the bus address to write from the master to slave
i2c_write(EEPROM_BUS_ADDRESS);
// tell the slave (EEPROM) which address will be read
i2c_write(address);
// Now the slave knows which address will be read
// Start signal
i2c_start();
// '1' shows the master read data from slave (data transfer direction?)
i2c_write(EEPROM_BUS_ADDRESS | 1);
// Finally, read the byte from the bus
data=i2c_read(0);
i2c_stop();
return data;
}


/* write a byte to the EEPROM */
// address => where we want the data to be stored
// data => actual data to be stored
void eeprom_write(unsigned int address, unsigned char data) 
{
i2c_start();
i2c_write(EEPROM_BUS_ADDRESS);
i2c_write(address);
i2c_write(data);
i2c_stop();
}

// Temperature sensor Reset Function
void reset()
{
DQ_OUT;
DQ_0;
// delay_us(480);
delay_us(500);
DQ_1;
delay_us(60);
DQ_IN;      // What happens if we don't have pull-up resistor? 
while(DQ);
while(!DQ);
}

// Sensor write function
void write(unsigned char data)
{
unsigned char i;
DQ_OUT;
for (i = 0;i<8;i++) 
    {
    DQ_0;
    delay_us(10); 
    
    if(data&0x01) 
    {DQ_1;}
    else {DQ_0;}  
    
    delay_us(40);
    DQ_1;
    delay_us(1);
    data >>= 1; 
  
    }

}

// Sensor read function
// Read the data sent from the sensor 
unsigned char read()
{

unsigned char i,temp;
for(i=0;i<8;i++)
    {
    // Initialize the sensor with low level input 
    DQ_OUT;
    DQ_0;         
    // I suppose the DQ might not receive 0 if there is no time delay.
    delay_us(2);
    // set up the MCU by switching to input mode with pull-up resistor    
    DQ_1; 
    DQ_IN; 
    // Read the PIN and determine the current bit value
    if(DQ) 
        {
        temp |= 0x80;} 
    
    temp >>= 1;  
    delay_us(45); 
    // 
    }
return temp;
}

// Read temperature function
// OUTPUT: temperature unsigned int value
unsigned int read_tem()
{
unsigned int tem1, tem2;
reset();
write(0xCC);
write(0x44);
reset();
write(0xCC);
write(0xBE);

tem1 = read();
tem2 = read();
return ((tem2<<8) | tem1) * 6.25;
}

// show temperature to LCD function
// INPUT: temperature value
void show_tem(unsigned int tem)
{
int ten, one, dat, dat1;
ten = tem/1000 + 0x30;
one = tem%1000/100 + 0x30;
dat = tem%100/10 + 0x30;
dat1= tem%10 + 0x30;

lcd_putsf("T = ");
// lcd_putchar(ten);
lcd_putchar(one);
lcd_putchar(dat);
lcd_putchar(0x2E);
lcd_putchar(dat1);
lcd_putsf("C");
}

void main(void)
{
// Declare your local variables here

// Variables, unsigned int, to store the temperature
unsigned int one, two, three, four, five;
unsigned int mean_value;

// Input/Output Ports initialization
// Port A initialization
// Function: Bit7=In Bit6=In Bit5=In Bit4=In Bit3=In Bit2=In Bit1=In Bit0=In 
DDRA=(0<<DDA7) | (0<<DDA6) | (0<<DDA5) | (0<<DDA4) | (0<<DDA3) | (0<<DDA2) | (0<<DDA1) | (0<<DDA0);
// State: Bit7=T Bit6=T Bit5=T Bit4=T Bit3=T Bit2=T Bit1=T Bit0=T 
PORTA=(0<<PORTA7) | (0<<PORTA6) | (0<<PORTA5) | (0<<PORTA4) | (0<<PORTA3) | (0<<PORTA2) | (0<<PORTA1) | (0<<PORTA0);

// Port B initialization
// Function: Bit7=In Bit6=In Bit5=In Bit4=In Bit3=In Bit2=In Bit1=In Bit0=In 
DDRB=(0<<DDB7) | (0<<DDB6) | (0<<DDB5) | (0<<DDB4) | (0<<DDB3) | (0<<DDB2) | (0<<DDB1) | (0<<DDB0);
// State: Bit7=T Bit6=T Bit5=T Bit4=T Bit3=T Bit2=T Bit1=T Bit0=T 
PORTB=(0<<PORTB7) | (0<<PORTB6) | (0<<PORTB5) | (0<<PORTB4) | (0<<PORTB3) | (0<<PORTB2) | (0<<PORTB1) | (0<<PORTB0);

// Port C initialization
// Function: Bit7=In Bit6=In Bit5=In Bit4=In Bit3=In Bit2=In Bit1=In Bit0=In 
DDRC=(0<<DDC7) | (0<<DDC6) | (0<<DDC5) | (0<<DDC4) | (0<<DDC3) | (0<<DDC2) | (0<<DDC1) | (0<<DDC0);
// State: Bit7=T Bit6=T Bit5=T Bit4=T Bit3=T Bit2=T Bit1=T Bit0=T 
PORTC=(0<<PORTC7) | (0<<PORTC6) | (0<<PORTC5) | (0<<PORTC4) | (0<<PORTC3) | (0<<PORTC2) | (0<<PORTC1) | (0<<PORTC0);

// Port D initialization
// Function: Bit7=In Bit6=In Bit5=In Bit4=In Bit3=In Bit2=In Bit1=In Bit0=In 
DDRD=(0<<DDD7) | (0<<DDD6) | (0<<DDD5) | (0<<DDD4) | (0<<DDD3) | (0<<DDD2) | (0<<DDD1) | (0<<DDD0);
// State: Bit7=T Bit6=T Bit5=T Bit4=T Bit3=T Bit2=T Bit1=T Bit0=T 
PORTD=(0<<PORTD7) | (0<<PORTD6) | (0<<PORTD5) | (0<<PORTD4) | (0<<PORTD3) | (0<<PORTD2) | (0<<PORTD1) | (0<<PORTD0);

// Timer/Counter 0 initialization
// Clock source: System Clock
// Clock value: Timer 0 Stopped
// Mode: Normal top=0xFF
// OC0 output: Disconnected
TCCR0=(0<<WGM00) | (0<<COM01) | (0<<COM00) | (0<<WGM01) | (0<<CS02) | (0<<CS01) | (0<<CS00);
TCNT0=0x00;
OCR0=0x00;

// Timer/Counter 1 initialization
// Clock source: System Clock
// Clock value: Timer1 Stopped
// Mode: Normal top=0xFFFF
// OC1A output: Disconnected
// OC1B output: Disconnected
// Noise Canceler: Off
// Input Capture on Falling Edge
// Timer1 Overflow Interrupt: Off
// Input Capture Interrupt: Off
// Compare A Match Interrupt: Off
// Compare B Match Interrupt: Off
TCCR1A=(0<<COM1A1) | (0<<COM1A0) | (0<<COM1B1) | (0<<COM1B0) | (0<<WGM11) | (0<<WGM10);
TCCR1B=(0<<ICNC1) | (0<<ICES1) | (0<<WGM13) | (0<<WGM12) | (0<<CS12) | (0<<CS11) | (0<<CS10);
TCNT1H=0x00;
TCNT1L=0x00;
ICR1H=0x00;
ICR1L=0x00;
OCR1AH=0x00;
OCR1AL=0x00;
OCR1BH=0x00;
OCR1BL=0x00;

// Timer/Counter 2 initialization
// Clock source: System Clock
// Clock value: Timer2 Stopped
// Mode: Normal top=0xFF
// OC2 output: Disconnected
ASSR=0<<AS2;
TCCR2=(0<<PWM2) | (0<<COM21) | (0<<COM20) | (0<<CTC2) | (0<<CS22) | (0<<CS21) | (0<<CS20);
TCNT2=0x00;
OCR2=0x00;

// Timer(s)/Counter(s) Interrupt(s) initialization
TIMSK=(0<<OCIE2) | (0<<TOIE2) | (0<<TICIE1) | (0<<OCIE1A) | (0<<OCIE1B) | (0<<TOIE1) | (0<<OCIE0) | (0<<TOIE0);

// External Interrupt(s) initialization
// INT0: Off
// INT1: Off
// INT2: Off
MCUCR=(0<<ISC11) | (0<<ISC10) | (0<<ISC01) | (0<<ISC00);
MCUCSR=(0<<ISC2);

// USART initialization
// USART disabled
UCSRB=(0<<RXCIE) | (0<<TXCIE) | (0<<UDRIE) | (0<<RXEN) | (0<<TXEN) | (0<<UCSZ2) | (0<<RXB8) | (0<<TXB8);

// Analog Comparator initialization
// Analog Comparator: Off
// The Analog Comparator's positive input is
// connected to the AIN0 pin
// The Analog Comparator's negative input is
// connected to the AIN1 pin
ACSR=(1<<ACD) | (0<<ACBG) | (0<<ACO) | (0<<ACI) | (0<<ACIE) | (0<<ACIC) | (0<<ACIS1) | (0<<ACIS0);
SFIOR=(0<<ACME);

// ADC initialization
// ADC disabled
ADCSRA=(0<<ADEN) | (0<<ADSC) | (0<<ADATE) | (0<<ADIF) | (0<<ADIE) | (0<<ADPS2) | (0<<ADPS1) | (0<<ADPS0);

// SPI initialization
// SPI disabled
SPCR=(0<<SPIE) | (0<<SPE) | (0<<DORD) | (0<<MSTR) | (0<<CPOL) | (0<<CPHA) | (0<<SPR1) | (0<<SPR0);

// TWI initialization
// TWI disabled
TWCR=(0<<TWEA) | (0<<TWSTA) | (0<<TWSTO) | (0<<TWEN) | (0<<TWIE);

// Bit-Banged I2C Bus initialization
// SDA signal: PORTC bit: 1
// SCL signal: PORTC bit: 0
// Bit Rate: 100 kHz
// Note: I2C settings are specified in the
// Project|Configure|C Compiler|Libraries|I2C menu.
i2c_init();

// 1 Wire Bus initialization
// 1 Wire Data port: PORTC
// 1 Wire Data bit: 7
// Note: 1 Wire port settings are specified in the
// Project|Configure|C Compiler|Libraries|1 Wire menu.
w1_init();

// Alphanumeric LCD initialization
// Connections are specified in the
// Project|Configure|C Compiler|Libraries|Alphanumeric LCD menu:
// RS: PORTB Bit 0
// RD: PORTB Bit 1
// EN: PORTB Bit 2
// D4: PORTD Bit 4
// D5: PORTD Bit 5
// D6: PORTD Bit 6
// D7: PORTD Bit 7
// Characters/line: 16
lcd_init(16);
// Task 1: Drive the DS18B20 chip to measure temperature, and use an LCD to display the readings, creating a thermometer.
/*
while (1)
      {
      // Place your code here
      show_tem(read_tem());
      delay_ms(500);
      lcd_clear();
      }    
*/

// Task 2: Every 1 second, retrieve the current temperature and store the integer value in the AT24C02. 
// After collecting 5 temperatures, read them back, calculate the average, and display it on the LCD.
while (1)
    {
    one = read_tem();
    eeprom_write(0x00, one);
    delay_ms(1000); 
    
    two = read_tem(); 
    eeprom_write(0x01, two);
    delay_ms(1000);    
    
    three = read_tem();  
    eeprom_write(0x02, three);
    delay_ms(1000);  
    
    four = read_tem();  
    eeprom_write(0x03, four);
    delay_ms(1000);    
    
    five = read_tem();     
    eeprom_write(0x04, five);
    delay_ms(1000);    
    
    // read the values to the same variables
    one = eeprom_read(0x00);
    two = eeprom_read(0x01);
    three = eeprom_read(0x02);
    four = eeprom_read(0x03);
    five = eeprom_read(0x04);
    mean_value = (one+two+three+four+five) / 5;
    
    // display the mean value to LCD
    show_tem(mean_value);  
    lcd_gotoxy(0,0);
    }
}
