/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 24.1 and DSP System Toolbox 24.1.
 * Generated on: 19-Aug-2024 17:12:37
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 61
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 * Arithmetic        : fixed
 * Numerator         : s16,16 -> [-5.000000e-01 5.000000e-01)
 * Input             : s16,15 -> [-1 1)
 * Filter Internals  : Full Precision
 *   Output          : s33,31 -> [-2 2)  (auto determined)
 *   Product         : s29,31 -> [-1.250000e-01 1.250000e-01)  (auto determined)
 *   Accumulator     : s33,31 -> [-2 2)  (auto determined)
 *   Round Mode      : No rounding
 *   Overflow Mode   : No overflow
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2024a\extern\include\tmwtypes.h 
 */
const int BL = 61;
const int16_T B[61] = {
        0,      1,      2,      3,      3,      0,     -9,    -25,    -50,
      -85,   -129,   -179,   -229,   -271,   -292,   -279,   -217,    -91,
      111,    399,    775,   1235,   1767,   2350,   2957,   3556,   4111,
     4587,   4953,   5183,   5261,   5183,   4953,   4587,   4111,   3556,
     2957,   2350,   1767,   1235,    775,    399,    111,    -91,   -217,
     -279,   -292,   -271,   -229,   -179,   -129,    -85,    -50,    -25,
       -9,      0,      3,      3,      2,      1,      0
};
